use_frameworks!

platform :ios, '10.0'

target 'LXYRouter_Example' do
  pod 'LXYRouter', :path => '../'

  target 'LXYRouter_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
